### ISSUE TITLE
How to include the hidden files/directories?

### ISSUE THREAD

**Issue by IonicaBizau** [ctalkington/node-archiver#110]
I guess that the trick should be in `src` array passed to the `bulk` function.

**Comment by ctalkington** [comment]
thats a good question. so your not seeing hidden files in the archive?

sometimes hidden files are in dot folders too so you would most likely need `['.*/**/*', '.*/*']` or `dot: true`. haven't personally tried this but should get you going in direction.

> Include .dot files in normal matches and globstar matches. Note that an explicit dot in a portion of the pattern will always match dot files.

bulk relies on glob to provide the list and it should work beyond that.

**Comment by IonicaBizau** [comment]
I actually need to archive a git repository, including the `.git` directory. When I do: `src: ['.*/**/*', '.*/*']`, nothing happens... 

If I remove the `src` and add `dot: true`, I get:

```sh
     var exclusion = pattern.indexOf('!') === 0;
                            ^
TypeError: Cannot call method 'indexOf' of undefined
```
(/lib/util/file.js:26)

**Comment by ctalkington** [comment]
sorry it would be:

`dot: true` with `src: ['**/*']` most likely.

i personally haven't done this but its just a matter of finding the right glob pattern.

**Comment by IonicaBizau** [comment]
Thanks!

`**/*` didn't include the `.git` directory. However `.git/**/*` worked.

```js
{ expand: true, src: ["*", ".git/**/*"], cwd: "...", dest: "..." }
```

One more question: how can I include all directories and files, recursively? The correspondent of `zip -r foo.zip foo/`.

**Comment by ctalkington** [comment]
`**` should cover that with `dot:true` to make it match any dot files, i imagine

**Comment by IonicaBizau** [comment]
Thanks!
