### ISSUE TITLE
Zipped directories get 0700 octal chmod by default

### ISSUE THREAD

**Issue by manakor** [ctalkington/node-archiver#111]
When zipping a directory, its subdirectories get 0700 octal permissions by default, instead of [0755 mentioned in the documentation](https://github.com/ctalkington/node-archiver#mode-number).

Here's initial directory structure (notice octal permissions):
````bash
 644 -rw-r--r--   1 manakor  admin    356 18 Jan 15:19 index.html
 755 drwxr-xr-x   6 manakor  admin    204 13 Jan 13:40 fonts
 755 drwxr-xr-x  30 manakor  admin   1020 18 Jan 15:36 images
 755 drwxr-xr-x   3 manakor  admin    102 18 Jan 15:19 scripts
 755 drwxr-xr-x   4 manakor  admin    136 18 Jan 15:36 styles
````

Zipping it:
````js
var fs = require('fs');
var archiver = require('archiver');

var output = fs.createWriteStream('package.zip');
var archive = archiver('zip');

output.on('close', function() {
  console.log('%s => %d bytes', 'package.zip', archive.pointer());
});

archive.on('error', function(err) {
  throw err;
});

archive.pipe(output);

archive.bulk([{
  expand: true,
  cwd: './website',
  src: ['**'],
  dest: './'
}]);

archive.finalize();
````

Getting an archive `package.zip ` with everything from a `./website` directory zipped in. All fine till now. When unzipping an archive on Mac with a double click, a new `package/` dir is created with the following structure (see octal permissions):
````bash
 644 -rw-r--r--   1 manakor  admin   2399 18 Jan 15:31 index.html
 700 drwx------   6 manakor  admin    204 18 Jan 15:31 fonts
 700 drwx------  30 manakor  admin   1020 18 Jan 15:31 images
 700 drwx------   3 manakor  admin    102 18 Jan 15:31 scripts
 700 drwx------   3 manakor  admin    102 18 Jan 15:31 styles
````

As you can see, `index.html` file has its original chmod 0644 and directories has 0700 instead of their original 0755. I guess it might be a default permissions assignment bug?

**Comment by ctalkington** [comment]
the data should be coming from stat. however if there is a bug its most likely coming from:

https://github.com/ctalkington/node-archiver/blob/master/lib/core.js#L193

or 

https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-entry.js#L201

oh how i love octals and bitwise operations.

**Comment by ctalkington** [comment]
so i made a test, and it seems to be preserved for me but i need to write another test for the actual zip format which is harder atm since the unzip node module doesn't provide that info.

its on my radar to work on in the next week or so once i handle some paid work.

**Comment by manakor** [comment]
Perfect, thanks. I'll try to have a look at lines you have pointed if I have time soon.

**Comment by ctalkington** [comment]
playing around with the code, havent found any glaring issues yet though im on windows so its harder to test permissions.

what version of mac do you have? also you may with unzip vs archiver utility as im not certain to what level zip permissions are supported by it.

**Comment by ctalkington** [comment]
also if youd like to email me a generated zip, i can do some tests on my end to see what the value in the archive actually is

**Comment by manakor** [comment]
![screen shot 2015-01-24 at 09 59 54](https://cloud.githubusercontent.com/assets/175385/5886771/eeecb3a0-a3af-11e4-8d23-22faa7922544.png)

Emailed you an archive.

**Comment by ctalkington** [comment]
@manakor ive tested this zip all the files come back as 420 decimal (or 644) and directories come back as 493 decimal (or 755).

at this point id say the mac archive utility is trying to prevent security issues or that it is ignoring the permissions which is an optional feature of zip.

also i noticed a `./` path inside the zip, you should most likely change your dest to blank or something other than `./`. also what version of archiver did you use to make this?

**Comment by ctalkington** [comment]
here is the test that i did:

```js
// npm install yauzl
var yauzl = require('yauzl');

yauzl.open('1422089983945.zip', function(err, zip) {
  zip.on('entry', function(entry) {
    var mode = (entry.externalFileAttributes >>> 16) & 0xFFF;
    console.log([entry.fileName, mode.toString(8)]);
  });

  zip.on('close', function() {
    console.log('end of archive');
  });
});
```

**Comment by manakor** [comment]
![screen shot 2015-01-26 at 22 31 54](https://cloud.githubusercontent.com/assets/175385/5908880/8def4aec-a5ab-11e4-8aa1-c972abffd8bc.png)

Tried your sample snippet ([previous comment](https://github.com/ctalkington/node-archiver/issues/111#issuecomment-71346394)) to unzip an archive and it turned to 755 for directories.
Then I confirm, it's not npm module issue, **but Archive Utility** on Mac.
