### ISSUE TITLE
Incorrect handling of cyrillic file names

### ISSUE THREAD

**Issue by vladimirgrezin** [ctalkington/node-archiver#115]
It seems like it had been fixed in https://github.com/ctalkington/node-archiver/commit/fa9d3ce0beef75301fe7bfdb29e1fa57a634e73c
But now it doesn't work again

**Comment by ctalkington** [comment]
all that logic had been moved out to compress-commons

https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-entry.js#L174

is used not to detect when the length is different from string length, ie a good sign the name isnt just basic text.

it is then stored in a buffer

https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L300

if you believe this doesn't work, feel free to provide a test on that repo similar to 

https://github.com/ctalkington/node-compress-commons/blob/master/test/zip-archive-entry.js#L217

**Comment by ctalkington** [comment]
it should also be noted that not all unzip programs support encoding fully, such as windows builtin. i hear 7zip tends to be the most friendly.

**Comment by vladimirgrezin** [comment]
The problem really was in windows unzip. With 7zip all works fine.
Thx for quick answer.

2015-01-28 11:30 GMT+03:00 Chris Talkington <notifications@github.com>:

> it should also be noted that not all unzip programs support encoding
> fully, such as windows builtin. i hear 7zip tends to be the most friendly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ctalkington/node-archiver/issues/115#issuecomment-71797780>
> .
>



-- 
С уважением,
Грезин Владимир
