### ISSUE TITLE
Long hold time at the end?

### ISSUE THREAD

**Issue by btmdave** [ctalkington/node-archiver#119]
This seems to be somewhat intermittent, but it will go like 95% fast, then the last bit will hang for a minute or two until it finishes.

**Comment by btmdave** [comment]
It seems to just not be fully finalizing.  After a few seconds, if I kill the server, it's complete and the file is fine.

**Comment by btmdave** [comment]
Ok, this seems to be isolated to when defining `Content-Length`, perhaps the content-length is larger than the actual files.

**Comment by btmdave** [comment]
I guess the question here is, is there anyway to get the `Content-Length` of the zip since it's streaming? 

Thanks a lot

**Comment by ctalkington** [comment]
what api are you using to stream via http with? there is an example of how express should work in this repo fyi.

**Comment by btmdave** [comment]
Yes I'm using express, it works, but since there's no content length you can't tell how much longer you have to download, so I was wondering if there's a way to get the content length of the zip to add to the header

**Comment by ctalkington** [comment]
that wouldn't be know as your streaming after all. size is variable. i personally dont use archiver in this fashion so you might get more info from other users.

**Comment by btmdave** [comment]
Yeah, I wonder if it could be piped to a variable? then could get the length and send it, granted this will use memory...

**Comment by ctalkington** [comment]
in regards to the hanging at end, i've noticed similar in a few tests when debugging #114. its like the streams can get stuck near the end or something.

whats the platform versions your working with?

**Comment by ctalkington** [comment]
if your wanting to go the route of not streaming direct, best i guess would be tmp file that you get stat and get size + stream from. could cause some issues in ux though.

**Comment by btmdave** [comment]
Well this was because I was setting content length based on the total size of all the files (not the zip file size), so it was waiting, thinking the file should be bigger, once I removed the content length, I haven't had any issues thus far.  I imagine this could potentially be an issue in some browsers (no content length), but not certain

**Comment by ctalkington** [comment]
that makes sense, i think most browsers will handle it ok and i think most http libs prob have catches for such as not everything is a defined size when doing exports etc.

**Comment by btmdave** [comment]
Re: tmp file, yeah... that's what I was hoping to get away from.  I believe nginx mod zip module is able to stream but still sends a content length, will do a little digging

**Comment by ctalkington** [comment]
yah i think ive seen some sites that things start out undefined and then get an end size somehow. so there may be a mechanism

**Comment by btmdave** [comment]
Cool well I'll update if I'm able to find out anything, thanks for your help!

**Comment by ctalkington** [comment]
http://stackoverflow.com/a/9728553

**Comment by ctalkington** [comment]
it would appear that express may auto use the `chunked` transfer encoding from quick google search. not sure the extent of how thats handled just fyi.

**Comment by btmdave** [comment]
Yep, it's chunked.  So your right, it's not possible in this fashion.
